package me.frodenkvist.utils;

import org.bukkit.Material;


public class MaterialFromInt {
	public static Material getMaterialFromInt(int id){
		org.bukkit.Material mat = Material.AIR;
		switch(id){
		case 0: mat = Material.AIR;
		break;
		case 1: mat = Material.STONE;
		break;
		case 2: mat = Material.GRASS;
		break;
		case 3: mat = Material.DIRT;
		break;
		case 4: mat = Material.COBBLESTONE;
		break;
		case 5: mat = Material.WOOD;
		break;
		case 6: mat = Material.SAPLING;
		break;
		case 7: mat = Material.BEDROCK;
		break;
		case 8: mat = Material.WATER;
		break;
		case 9: mat = Material.STATIONARY_WATER;
		break;
		case 10: mat = Material.LAVA;
		break;
		case 11: mat = Material.STATIONARY_LAVA;
		break;
		case 12: mat = Material.SAND;
		break;
		case 13: mat = Material.GRAVEL;
		break;
		case 14: mat = Material.GOLD_ORE;
		break;
		case 15: mat = Material.IRON_ORE;
		break;
		case 16: mat = Material.COAL_ORE;
		break;
		case 17: mat = Material.LOG;
		break;
		case 18: mat = Material.LEAVES;
		break;
		case 19: mat = Material.SPONGE;
		break;
		case 20: mat = Material.GLASS;
		break;
		case 21: mat = Material.LAPIS_ORE;
		break;
		case 22: mat = Material.LAPIS_BLOCK;
		break;		
		case 23: mat = Material.DISPENSER;
		break;
		case 24: mat = Material.SANDSTONE;
		break;
		case 25: mat = Material.NOTE_BLOCK;
		break;
		case 26: mat = Material.BED_BLOCK;
		break;
		case 27: mat = Material.POWERED_RAIL;
		break;
		case 28: mat = Material.DETECTOR_RAIL;
		break;
		case 29: mat = Material.PISTON_STICKY_BASE;
		break;
		case 30: mat = Material.WEB;
		break;
		case 31: mat = Material.DEAD_BUSH;
		break;
		case 32: mat = Material.DEAD_BUSH;
		break;
		case 33: mat = Material.PISTON_BASE;
		break;
		case 34: mat = Material.PISTON_MOVING_PIECE;
		break;		
		case 35: mat = Material.WOOL;
		break;
		case 36: mat = Material.AIR;
		break;
		case 37: mat = Material.YELLOW_FLOWER;
		break;
		case 38: mat = Material.RED_ROSE;
		break;
		case 39: mat = Material.BROWN_MUSHROOM;
		break;
		case 40: mat = Material.RED_MUSHROOM;
		break;
		case 41: mat = Material.GOLD_BLOCK;
		break;
		case 42: mat = Material.IRON_BLOCK;
		break;
		case 43: mat = Material.DOUBLE_STEP;
		break;
		case 44: mat = Material.STEP;
		break;
		case 45: mat = Material.BRICK;
		break;
		case 46: mat = Material.TNT;
		break;		
		case 47: mat = Material.BOOKSHELF;
		break;
		case 48: mat = Material.MOSSY_COBBLESTONE;
		break;
		case 49: mat = Material.OBSIDIAN;
		break;
		case 50: mat = Material.TORCH;
		break;
		case 51: mat = Material.FIRE;
		break;
		case 52: mat = Material.MOB_SPAWNER;
		break;
		case 53: mat = Material.WOOD_STAIRS;
		break;
		case 54: mat = Material.CHEST;
		break;
		case 55: mat = Material.REDSTONE_WIRE;
		break;
		case 56: mat = Material.DIAMOND_ORE;
		break;		
		case 57: mat = Material.DIAMOND_BLOCK;
		break;
		case 58: mat = Material.WORKBENCH;
		break;
		case 59: mat = Material.CROPS;
		break;
		case 60: mat = Material.SOIL;
		break;
		case 61: mat = Material.FURNACE;
		break;
		case 62: mat = Material.BURNING_FURNACE;
		break;
		case 63: mat = Material.SIGN_POST;
		break;
		case 64: mat = Material.WOOD_DOOR;
		break;
		case 65: mat = Material.LADDER;
		break;
		case 66: mat = Material.RAILS;
		break;		
		case 67: mat = Material.COBBLESTONE_STAIRS;
		break;
		case 68: mat = Material.WALL_SIGN;
		break;
		case 69: mat = Material.LEVER;
		break;
		case 70: mat = Material.STONE_PLATE;
		break;
		case 71: mat = Material.IRON_DOOR_BLOCK;
		break;
		case 72: mat = Material.WOOD_PLATE;
		break;
		case 73: mat = Material.REDSTONE_ORE;
		break;
		case 74: mat = Material.GLOWING_REDSTONE_ORE;
		break;
		case 75: mat = Material.REDSTONE_TORCH_OFF;
		break;
		case 76: mat = Material.REDSTONE_TORCH_ON;
		break;		
		case 77: mat = Material.STONE_BUTTON;
		break;
		case 78: mat = Material.SNOW;
		break;
		case 79: mat = Material.ICE;
		break;
		case 80: mat = Material.SNOW_BLOCK;
		break;
		case 81: mat = Material.CACTUS;
		break;
		case 82: mat = Material.CLAY;
		break;
		case 83: mat = Material.SUGAR_CANE;
		break;
		case 84: mat = Material.JUKEBOX;
		break;
		case 85: mat = Material.FENCE;
		break;
		case 86: mat = Material.PUMPKIN;
		break;		
		case 88: mat = Material.SOUL_SAND;
		break;
		case 89: mat = Material.GLOWSTONE;
		break;
		case 90: mat = Material.PORTAL;
		break;
		case 91: mat = Material.JACK_O_LANTERN;
		break;
		case 92: mat = Material.CAKE_BLOCK;
		break;
		case 93: mat = Material.REDSTONE_COMPARATOR_ON;
		break;
		case 94: mat = Material.REDSTONE_COMPARATOR_OFF;
		break;
		case 95: mat = Material.LOCKED_CHEST;
		break;
		case 96: mat = Material.TRAP_DOOR;
		break;
		case 97: mat = Material.STONE;
		break;
		case 98: mat = Material.SMOOTH_BRICK;
		break;		
		case 99: mat = Material.HUGE_MUSHROOM_1;
		break;
		case 100: mat = Material.HUGE_MUSHROOM_2;
		break;
		case 101: mat = Material.IRON_FENCE;
		break;
		case 102: mat = Material.THIN_GLASS;
		break;
		case 103: mat = Material.MELON_BLOCK;
		break;
		case 104: mat = Material.PUMPKIN_STEM;
		break;
		case 105: mat = Material.MELON_STEM;
		break;
		case 106: mat = Material.VINE;
		break;
		case 107: mat = Material.FENCE_GATE;
		break;
		case 108: mat = Material.BRICK_STAIRS;
		break;		
		case 109: mat = Material.SMOOTH_STAIRS;
		break;
		case 110: mat = Material.MYCEL;
		break;
		case 111: mat = Material.WATER_LILY;
		break;
		case 112: mat = Material.NETHER_BRICK;
		break;
		case 113: mat = Material.NETHER_FENCE;
		break;
		case 114: mat = Material.NETHER_BRICK_STAIRS;
		break;
		case 115: mat = Material.NETHER_WARTS;
		break;
		case 116: mat = Material.ENCHANTMENT_TABLE;
		break;
		case 117: mat = Material.BREWING_STAND;
		break;
		case 118: mat = Material.CAULDRON;
		break;		
		case 119: mat = Material.ENDER_PORTAL;
		break;
		case 120: mat = Material.ENDER_PORTAL_FRAME;
		break;
		case 121: mat = Material.ENDER_STONE;
		break;
		case 122: mat = Material.DRAGON_EGG;
		break;
		case 123: mat = Material.REDSTONE_LAMP_OFF;
		break;
		case 124: mat = Material.REDSTONE_LAMP_ON;
		break;
		case 125: mat = Material.WOOD;
		break;
		case 126: mat = Material.WOOD_STEP;
		break;
		case 127: mat = Material.COCOA;
		break;
		case 128: mat = Material.SANDSTONE_STAIRS;
		break;		
		case 129: mat = Material.EMERALD_ORE;
		break;
		case 130: mat = Material.ENDER_CHEST;
		break;
		case 131: mat = Material.TRIPWIRE_HOOK;
		break;
		case 132: mat = Material.TRIPWIRE;
		break;
		case 133: mat = Material.EMERALD_BLOCK;
		break;
		case 134: mat = Material.SPRUCE_WOOD_STAIRS;
		break;
		case 135: mat = Material.BIRCH_WOOD_STAIRS;
		break;
		case 136: mat = Material.JUNGLE_WOOD_STAIRS;
		break;
		case 137: mat = Material.COMMAND;
		break;
		case 138: mat = Material.BEACON;
		break;		
		case 139: mat = Material.COBBLE_WALL;
		break;
		case 140: mat = Material.FLOWER_POT;
		break;
		case 141: mat = Material.CARROT;
		break;
		case 142: mat = Material.POTATO;
		break;
		case 143: mat = Material.WOOD_BUTTON;
		break;
		case 144: mat = Material.SKULL_ITEM;
		break;
		case 145: mat = Material.ANVIL;
		break;
		case 146: mat = Material.TRAPPED_CHEST;
		break;
		case 147: mat = Material.GOLD_PLATE;
		break;
		case 148: mat = Material.IRON_PLATE;
		break;		
		case 149: mat = Material.REDSTONE_COMPARATOR_OFF;
		break;
		case 150: mat = Material.REDSTONE_COMPARATOR_ON;
		break;
		case 151: mat = Material.DAYLIGHT_DETECTOR;
		break;
		case 152: mat = Material.REDSTONE_BLOCK;
		break;
		case 153: mat = Material.QUARTZ_ORE;
		break;
		case 154: mat = Material.HOPPER;
		break;
		case 155: mat = Material.QUARTZ_BLOCK;
		break;
		case 156: mat = Material.QUARTZ_STAIRS;
		break;
		case 157: mat = Material.ACTIVATOR_RAIL;
		break;
		case 158: mat = Material.DROPPER;
		break;		
		case 159: mat = Material.CLAY;
		break;
		case 160: 
		break;
		case 161: 
		break;
		case 162: 
		break;
		case 163: 
		break;
		case 164: 
		break;
		case 165: 
		break;
		case 166: 
		break;
		case 167: 
		break;
		case 168: 
		break;		
		case 169:
		break;
		case 170: mat = Material.HAY_BLOCK;
		break; 
		case 171: mat = Material.CARPET;
		break;
		case 172: mat = Material.HARD_CLAY;
		break;
		case 173: mat = Material.COAL_BLOCK;
		break;
		case 256: mat = Material.IRON_SPADE;
		break;
		case 257: mat = Material.IRON_PICKAXE;
		break;
		case 258: mat = Material.IRON_AXE;
		break;
		case 259: mat = Material.FLINT_AND_STEEL;
		break;
		case 260: mat = Material.APPLE;
		break;		
		case 261: mat = Material.BOW;
		break;
		case 262: mat = Material.ARROW;
		break;
		case 263: mat = Material.COAL;
		break;
		case 264: mat = Material.DIAMOND;
		break;
		case 265: mat = Material.IRON_INGOT;
		break;
		case 266: mat = Material.GOLD_INGOT;
		break;
		case 267: mat = Material.IRON_SWORD;
		break;
		case 268: mat = Material.WOOD_SWORD;
		break;
		case 269: mat = Material.WOOD_SPADE;
		break;
		case 270: mat = Material.WOOD_PICKAXE;
		break;		
		case 271: mat = Material.WOOD_AXE;
		break;
		case 272: mat = Material.STONE_SWORD;
		break;
		case 273: mat = Material.STONE_SPADE;
		break;
		case 274: mat = Material.STONE_PICKAXE;
		break;		
		case 275: mat = Material.STONE_AXE;
		break;
		case 276: mat = Material.DIAMOND_SWORD;
		break;
		case 277: mat = Material.DIAMOND_SPADE;
		break;
		case 278: mat = Material.DIAMOND_PICKAXE;
		break;		
		case 279: mat = Material.DIAMOND_AXE;
		break;
		case 280: mat = Material.STICK;
		break;
		case 281: mat = Material.BOWL;
		break;
		case 282: mat = Material.MUSHROOM_SOUP;
		break;
		case 283: mat = Material.GOLD_SWORD;
		break;
		case 284: mat = Material.GOLD_SPADE;
		break;
		case 285: mat = Material.GOLD_PICKAXE;
		break;		
		case 286: mat = Material.GOLD_AXE;
		break;
		case 287: mat = Material.STRING;
		break;
		case 288: mat = Material.FEATHER;
		break;
		case 289: mat = Material.SULPHUR;
		break;
		case 290: mat = Material.WOOD_HOE;
		break;
		case 291: mat = Material.STONE_HOE;
		break;
		case 292: mat = Material.IRON_HOE;
		break;		
		case 293: mat = Material.DIAMOND_HOE;
		break;
		case 294: mat = Material.GOLD_HOE;
		break;
		case 295: mat = Material.SEEDS;
		break;
		case 296: mat = Material.WHEAT;
		break;
		case 297: mat = Material.BREAD;
		break;
		case 298: mat = Material.LEATHER_HELMET;
		break;
		case 299: mat = Material.LEATHER_CHESTPLATE;
		break;
		case 300: mat = Material.LEATHER_LEGGINGS;
		break;
		case 301: mat = Material.LEATHER_BOOTS;
		break;
		case 302: mat = Material.CHAINMAIL_HELMET;
		break;
		case 303: mat = Material.CHAINMAIL_CHESTPLATE;
		break;
		case 304: mat = Material.CHAINMAIL_LEGGINGS;
		break;
		case 305: mat = Material.CHAINMAIL_BOOTS;
		break;
		case 306: mat = Material.GOLD_HELMET;
		break;
		case 307: mat = Material.GOLD_CHESTPLATE;
		break;
		case 308: mat = Material.GOLD_LEGGINGS;
		break;
		case 309: mat = Material.GOLD_BOOTS;
		break;
		case 310: mat = Material.DIAMOND_HELMET;
		break;
		case 311: mat = Material.DIAMOND_CHESTPLATE;
		break;
		case 312: mat = Material.DIAMOND_LEGGINGS;
		break;
		case 313: mat = Material.DIAMOND_BOOTS;
		break;
		case 314: mat = Material.GOLD_HELMET;
		break;
		case 315: mat = Material.GOLD_CHESTPLATE;
		break;
		case 316: mat = Material.GOLD_LEGGINGS;
		break;
		case 317: mat = Material.GOLD_BOOTS;
		break;
		case 318: mat = Material.FLINT;
		break;
		case 319: mat = Material.PORK;
		break;		
		case 320: mat = Material.PORK;
		break;
		case 321: mat = Material.PAINTING;
		break;
		case 322: mat = Material.GOLDEN_APPLE;
		break;		
		case 323: mat = Material.SIGN;
		break;
		case 324: mat = Material.WOODEN_DOOR;
		break;
		case 325: mat = Material.BUCKET;
		break;		
		case 326: mat = Material.WATER_BUCKET;
		break;
		case 327: mat = Material.LAVA_BUCKET;
		break;
		case 328: mat = Material.MINECART;
		break;		
		case 329: mat = Material.SADDLE;
		break;
		case 330: mat = Material.IRON_DOOR;
		break;
		case 331: mat = Material.REDSTONE;
		break;		
		case 332: mat = Material.SNOW_BALL;
		break;
		case 333: mat = Material.BOAT;
		break;
		case 334: mat = Material.LEATHER;
		break;
		case 335: mat = Material.MILK_BUCKET;
		break;		
		case 336: mat = Material.CLAY_BRICK;
		break;
		case 337: mat = Material.CLAY_BALL;
		break;
		case 338: mat = Material.SUGAR_CANE;
		break;		
		case 339: mat = Material.PAPER;
		break;
		case 340: mat = Material.BOOK;
		break;
		case 341: mat = Material.SLIME_BALL;
		break;		
		case 342: mat = Material.STORAGE_MINECART;
		break;
		case 343: mat = Material.POWERED_MINECART;
		break;
		case 344: mat = Material.EGG;
		break;
		case 345: mat = Material.COMPASS;
		break;		
		case 346: mat = Material.FISHING_ROD;
		break;
		case 347: mat = Material.WATCH;
		break;
		case 348: mat = Material.GLOWSTONE_DUST;
		break;		
		case 349: mat = Material.RAW_FISH;
		break;
		case 350: mat = Material.COOKED_FISH;
		break;
		case 351: mat = Material.INK_SACK;
		break;		
		case 352: mat = Material.BONE;
		break;
		case 353: mat = Material.SUGAR;
		break;
		case 354: mat = Material.CAKE;
		break;
		case 355: mat = Material.BED;
		break;		
		case 356: mat = Material.REDSTONE_BLOCK;
		break;
		case 357: mat = Material.COOKIE;
		break;
		case 358: mat = Material.MAP;
		break;		
		case 359: mat = Material.SHEARS;
		break;
		case 360: mat = Material.MELON;
		break;
		case 361: mat = Material.PUMPKIN_SEEDS;
		break;
		case 362: mat = Material.MELON_SEEDS;
		break;
		case 363: mat = Material.RAW_BEEF;
		break;
		case 364: mat = Material.COOKED_BEEF;
		break;
		case 365: mat = Material.RAW_CHICKEN;
		break;		
		case 366: mat = Material.COOKED_CHICKEN;
		break;
		case 367: mat = Material.ROTTEN_FLESH;
		break;
		case 368: mat = Material.ENDER_PEARL;
		break;		
		case 369: mat = Material.BLAZE_ROD;
		break;
		case 370: mat = Material.GHAST_TEAR;
		break;
		case 371: mat = Material.GOLD_NUGGET;
		break;
		case 372: mat = Material.NETHER_WARTS;
		break;
		case 373: mat = Material.POTION;
		break;
		case 374: mat = Material.GLASS_BOTTLE;
		break;
		case 375: mat = Material.SPIDER_EYE;
		break;		
		case 376: mat = Material.FERMENTED_SPIDER_EYE;
		break;
		case 377: mat = Material.BLAZE_POWDER;
		break;
		case 378: mat = Material.MAGMA_CREAM;
		break;		
		case 379: mat = Material.BREWING_STAND_ITEM;
		break;
		case 380: mat = Material.CAULDRON_ITEM;
		break;
		case 381: mat = Material.EYE_OF_ENDER;
		break;
		case 382: mat = Material.MELON;
		break;
		case 383: mat = Material.EGG;
		break;
		case 384: mat = Material.ENCHANTED_BOOK;
		break;
		case 385: mat = Material.FIREWORK_CHARGE;
		break;		
		case 386: mat = Material.BOOK_AND_QUILL;
		break;
		case 387: mat = Material.WRITTEN_BOOK;
		break;
		case 388: mat = Material.EMERALD;
		break;		
		case 389: mat = Material.ITEM_FRAME;
		break;
		case 390: mat = Material.FLOWER_POT_ITEM;
		break;
		case 391: mat = Material.CARROT_ITEM;
		break;
		case 392: mat = Material.POTATO_ITEM;
		break;
		case 393: mat = Material.BAKED_POTATO;
		break;
		case 394: mat = Material.POISONOUS_POTATO;
		break;
		case 395: mat = Material.MAP;
		break;		
		case 396: mat = Material.GOLDEN_CARROT;
		break;
		case 397: mat = Material.SKULL_ITEM;
		break;
		case 398: mat = Material.CARROT_STICK;
		break;		
		case 399: mat = Material.NETHER_STAR;
		break;
		case 400: mat = Material.PUMPKIN_PIE;
		break;
		case 401: mat = Material.FIREWORK;
		break;
		case 402: mat = Material.FIREWORK_CHARGE;
		break;
		case 403: mat = Material.ENCHANTED_BOOK;
		break;
		case 404: mat = Material.REDSTONE_COMPARATOR;
		break;
		case 405: mat = Material.NETHER_BRICK;
		break;		
		case 406: mat = Material.QUARTZ;
		break;
		case 407: mat = Material.TNT;
		break;
		case 408: mat = Material.HOPPER_MINECART;
		break;		
		case 417: mat = Material.IRON_BARDING;
		break;
		case 418: mat = Material.GOLD_BARDING;
		break;
		case 419: mat = Material.DIAMOND_BARDING;
		break;
		case 420: mat = Material.LEASH;
		break;
		case 421: mat = Material.NAME_TAG;
		break;
		default:  mat = Material.AIR;
		break;
		}
		return mat;
	}
}
